l=[10,20,30,40,"Ankii","Shiv"]
print("Type of object is: ",type(l))
l.append(70)
print("70 is appended: ",l)
l.pop(3)
print("Popped element :",l)
l.insert(4,"Dev")
print("Dev is inserted at 4th position: ",l)
l.clear()
print("clear list: ",l)

l1=["Anvita",12,3,135,3,"Shivtej"]
l1.copy()
print("Copied list: ",l1)
l1.remove(12)
print("Remove 12 from list: ",l1)
a=l1.count(3)
print("No of 3: ",a)
b= l1.index("Anvita")
print("Index of Anvita: ",b)
l1.reverse()
print("reversed List: ",l1)
l1.extend("Shivtej")
print(l1)