s="Hello Everyone"
print('a'not in s)
print('ll' in s)
#indexing
print(s[0:5])
print(s[1:11:3])
print(s[0:])
#function
print(s.casefold())
print(s.islower())
print(s.lower())
print(s.upper())
print(s.find('E'))
print(s.endswith('v'))
print(s.isascii())
print(s.isalpha())
print(s.isnumeric())
print(s.index('r'))
print(s.count('l'))
print(s.center(4))
print(s.isdecimal())
print(s.isdigit())
print(s.isidentifier())
print(s.isprintable())
print(s.replace('l' ,'e'))
print(s.lstrip())
print(s.strip())
